(async()=>{
  const C=SchoolCore,E=C.escapeHTML,$=selector=>document.querySelector(selector);let mode='local',tab='articles',data={articles:[],events:[]},api,user,busy=false;
  const seedContent=await fetch('content.json').then(r=>r.json());const seedEvents=(await fetch('events.json').then(r=>r.json())).events;
  const initialArticles=seedContent.records.filter(r=>r.type==='post').map(r=>({...r,id:String(r.id),published:true,category:C.articleCategory(r),featured:r.slug==='el-camino-del-practicante-de-artes-marciales',author:'',summary:''}));
  const localMode=!window.TAIKA_FIREBASE_CONFIG;
  $('#access-copy').textContent=localMode?'Firebase se conectará en la próxima etapa. Podés probar este panel: los cambios se guardan sólo en este navegador y se ven en una vista de prueba. No modifican el sitio público.':'Ingresá con tu cuenta autorizada para gestionar artículos y actividades.';
  $('#access-button').textContent=localMode?'Probar panel en este navegador':'Ingresar con Google';$('#access-button').disabled=false;
  function safeURL(value,media=false){return /^(https:\/\/|assets\/|#\/|mailto:)/i.test(value)||media&&/^data:image\/(jpeg|png|webp);base64,/i.test(value);}
  function cleanHTML(html){const doc=new DOMParser().parseFromString(html,'text/html');const allowed=new Set('P STRONG B EM I H2 H3 H4 UL OL LI BLOCKQUOTE BR IMG A FIGURE FIGCAPTION TABLE TBODY THEAD TR TD TH IFRAME SPAN HR'.split(' '));
    doc.querySelectorAll('script,style,object,embed,form,input,button,textarea,svg,math,template').forEach(el=>el.remove());
    [...doc.body.querySelectorAll('*')].reverse().forEach(el=>{if(!allowed.has(el.tagName)){el.replaceWith(...el.childNodes);return;}const src=el.getAttribute('src'),href=el.getAttribute('href'),alt=el.getAttribute('alt')||'';[...el.attributes].forEach(a=>el.removeAttribute(a.name));
      if(el.tagName==='IMG'){if(src&&safeURL(src,true)){el.setAttribute('src',src);el.setAttribute('alt',alt);el.setAttribute('loading','lazy');}else el.remove();}
      if(el.tagName==='A'&&href&&safeURL(href)){el.setAttribute('href',href);if(href.startsWith('https://')){el.setAttribute('target','_blank');el.setAttribute('rel','noopener');}}
      if(el.tagName==='IFRAME'){if(src&&/^https:\/\/(www\.)?(youtube\.com|youtube-nocookie\.com)\/embed\//.test(src)){el.setAttribute('src',src);el.setAttribute('title','Video de la escuela');el.setAttribute('loading','lazy');el.setAttribute('allowfullscreen','');}else el.remove();}
    });return doc.body.innerHTML;
  }
  function backup(){const blob=new Blob([JSON.stringify({...data,exportedAt:new Date().toISOString()},null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='taikachisu-contenido-respaldo.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
  function render(){$('#preview-site').href='index.html'+(mode==='local'?'?preview=1':'')+'#/'+(tab==='articles'?'camino-marcial':'calendario');const items=data[tab];$('#admin-count').textContent=`${items.length} ${tab==='articles'?'artículos':'actividades'}`;$('#new-item').textContent=tab==='articles'?'Nuevo artículo':'Nueva actividad';$('#admin-list').innerHTML=items.map(item=>`<article class="admin-list-row"><div><h2>${E(item.title)}</h2><p>${tab==='events'?E(C.dateLabel(item.date)):E(C.articleCategory(item))}</p></div><span>${item.published?'Publicado':'Borrador'}</span><button type="button" data-id="${E(item.id)}">Editar</button></article>`).join('');$('#admin-list').querySelectorAll('[data-id]').forEach(button=>button.addEventListener('click',()=>edit(items.find(item=>item.id===button.dataset.id))));}
  function edit(item={}){if(busy)return;$('#admin-editor').hidden=false;$('#editor-heading').textContent=tab==='articles'?(item.id?'Editar artículo':'Nuevo artículo'):(item.id?'Editar actividad':'Nueva actividad');$('#editor-form').reset();$('#item-id').value=item.id||'';$('#item-title').value=item.title||'';$('.article-fields').hidden=tab!=='articles';$('.event-fields').hidden=tab!=='events';$('#item-date').required=tab==='events';$('#item-body').innerHTML=cleanHTML(item.html||'');$('#item-category').value=C.articleCategory(item);$('#item-author').value=item.author||'';$('#item-summary').value=item.summary||'';$('#item-image').value=item.image||'';$('#item-featured').checked=Boolean(item.featured);$('#item-date').value=item.date||'';$('#item-time').value=item.time||'';$('#item-location').value=item.location||'';$('#item-sede').value=item.sede||'';$('#item-description').value=item.description||'';$('#item-attachment').value=item.attachment||'';$('#editor-message').textContent='';$('#publish-item').textContent=mode==='local'?'Publicar en vista de prueba':'Publicar';$('#admin-editor').scrollIntoView({behavior:'instant'});$('#item-title').focus({preventScroll:true});}
  async function save(published){if(busy||!$('#editor-form').reportValidity())return;const existing=data[tab].find(item=>item.id===$('#item-id').value);const title=$('#item-title').value.trim();const id=existing?.id||crypto.randomUUID();let item;
    try{if(tab==='events'){item={id,title,date:$('#item-date').value,time:$('#item-time').value,location:$('#item-location').value.trim(),sede:$('#item-sede').value,description:$('#item-description').value.trim(),attachment:$('#item-attachment').value.trim(),published};C.validateEvent(item);if(item.attachment&&!safeURL(item.attachment)&&!(mode==='local'&&/^data:(application\/pdf|image\/(jpeg|png|webp));base64,/.test(item.attachment)))throw new Error('El adjunto necesita un enlace HTTPS válido.');}
      else{const html=cleanHTML($('#item-body').innerHTML);const doc=new DOMParser().parseFromString(html,'text/html');const text=doc.body.textContent.trim();if(!text)throw new Error('Escribí el texto del artículo.');const image=$('#item-image').value.trim();if(image&&!safeURL(image,true))throw new Error('Usá un enlace HTTPS o subí una imagen.');const slug=existing?.slug||C.normalize(title).replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')+'-'+id.slice(0,6);item={id,title,slug,type:'post',html,text,image,category:$('#item-category').value,author:$('#item-author').value.trim(),summary:$('#item-summary').value.trim(),featured:$('#item-featured').checked,published};}
      busy=true;$('#publish-item').disabled=$('#save-draft').disabled=true;
      // Publishing a featured article replaces the previous feature atomically in local mode.
      const next=JSON.parse(JSON.stringify(data));if(tab==='articles'&&item.featured&&published){next.articles.forEach(article=>{article.featured=false;});}
      const index=next[tab].findIndex(record=>record.id===id);if(index<0)next[tab].push(item);else next[tab][index]=item;
      if(mode==='local')SchoolStore.localWrite(next);
      else{if(tab==='articles'&&item.featured&&published){const batch=api.db.writeBatch(api.database);for(const article of data.articles.filter(a=>a.featured&&a.id!==id))batch.update(api.db.doc(api.database,'articles',article.id),{featured:false});batch.set(api.db.doc(api.database,'articles',id),{...item,updatedAt:api.db.serverTimestamp()});await batch.commit();}else await SchoolStore.save(tab,item);}
      data=next;$('#item-id').value=id;render();$('#editor-message').textContent=mode==='local'?(published?'Publicado en la vista de prueba. El sitio público no cambió.':'Borrador guardado sólo en este navegador.'):(published?'Publicado en el sitio.':'Borrador guardado.');
    }catch(error){$('#editor-message').textContent=error.message||'No se pudo guardar. Reintentá.';}finally{busy=false;$('#publish-item').disabled=$('#save-draft').disabled=false;}
  }
  $('#access-button').addEventListener('click',async()=>{try{$('#access-button').disabled=true;if(localMode){mode='local';data=SchoolStore.localRead()||{articles:initialArticles,events:seedEvents};SchoolStore.localWrite(data);}else{mode='cloud';api=await SchoolStore.cloud();const result=await api.auth.signInWithPopup(api.authentication,new api.auth.GoogleAuthProvider());user=result.user;const token=await user.getIdTokenResult();if(token.claims.editor!==true){await api.auth.signOut(api.authentication);throw new Error('Esta cuenta no tiene permiso de edición.');}const state=await api.db.getDoc(api.db.doc(api.database,'site','content'));if(!state.exists()||!state.data().initialized){await SchoolStore.seed(initialArticles,seedEvents);}data={articles:await SchoolStore.list(api,'articles',true),events:await SchoolStore.list(api,'events',true)};}
    $('#admin-access').hidden=true;$('#admin-workspace').hidden=false;$('#admin-notice').textContent=mode==='local'?'MODO DE PRUEBA · Los cambios se guardan únicamente en este navegador. “Publicar” actualiza la vista de prueba, no el sitio público. Firebase se conectará en la próxima etapa.':'Sesión autorizada · Las publicaciones se muestran en el sitio. Los borradores son privados.';if(mode==='cloud'){$('#preview-site').href='index.html#/calendario';$('#preview-site').textContent='Ver sitio ↗';}render();}catch(error){$('#access-copy').textContent=error.message;}finally{$('#access-button').disabled=false;}});
  $('#admin-logout').addEventListener('click',async()=>{if(api)await api.auth.signOut(api.authentication);location.reload();});$('#export-backup').addEventListener('click',backup);$('#new-item').addEventListener('click',()=>edit());$('#close-editor').addEventListener('click',()=>{$('#admin-editor').hidden=true;});$('#editor-form').addEventListener('submit',e=>{e.preventDefault();save(false);});$('#publish-item').addEventListener('click',()=>save(true));
  document.querySelectorAll('[data-tab]').forEach(button=>button.addEventListener('click',()=>{if(busy)return;tab=button.dataset.tab;document.querySelectorAll('[data-tab]').forEach(b=>b.setAttribute('aria-pressed',String(b===button)));$('#admin-editor').hidden=true;render();}));
  document.querySelectorAll('[data-format]').forEach(button=>{button.addEventListener('mousedown',e=>e.preventDefault());button.addEventListener('click',()=>{const selection=getSelection();if(!selection.rangeCount)return;const range=selection.getRangeAt(0);if(!$('#item-body').contains(range.commonAncestorContainer))return;const tag=button.dataset.format;const wrapper=document.createElement(tag==='ul'?'li':tag);wrapper.append(range.extractContents());if(tag==='ul'){const list=document.createElement('ul');list.append(wrapper);range.insertNode(list);}else range.insertNode(wrapper);selection.removeAllRanges();const cursor=document.createRange();cursor.selectNodeContents(wrapper);selection.addRange(cursor);$('#item-body').focus();});});
  $('#item-body').addEventListener('paste',event=>{event.preventDefault();const text=event.clipboardData.getData('text/plain');const selection=getSelection();if(!selection.rangeCount)return;const range=selection.getRangeAt(0);range.deleteContents();const node=document.createTextNode(text);range.insertNode(node);range.setStartAfter(node);range.collapse(true);selection.removeAllRanges();selection.addRange(range);});
  async function upload(input,target){const file=input.files[0];if(!file)return;try{if(!(target==='#item-image'?['image/jpeg','image/png','image/webp']:['image/jpeg','image/png','image/webp','application/pdf']).includes(file.type)||file.size>5*1024*1024)throw new Error('Usá JPG, PNG, WebP o PDF de hasta 5 MB.');if(mode==='local'){if(file.size>1200*1024)throw new Error('Para la prueba local, elegí un archivo de hasta 1,2 MB.');const result=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=reject;reader.readAsDataURL(file);});$(target).value=result;}else{const ref=api.storage.ref(api.bucket,'public-media/'+crypto.randomUUID()+'/'+file.name.replace(/[^a-zA-Z0-9._-]/g,'_'));await api.storage.uploadBytes(ref,file);$(target).value=await api.storage.getDownloadURL(ref);}$('#editor-message').textContent='Archivo preparado. Guardá el contenido para conservarlo.';}catch(error){$('#editor-message').textContent=error.message;}}
  $('#image-upload').addEventListener('change',()=>upload($('#image-upload'),'#item-image'));$('#attachment-upload').addEventListener('change',()=>upload($('#attachment-upload'),'#item-attachment'));
})().catch(error=>{document.querySelector('#access-copy').textContent='No se pudo cargar el contenido del panel. Recargá la página.';console.error(error);});
